jwt:
  secret: 114514
  expire: 3600
server:
  port: 8080
  ver: v1
admin:
  username: admin
  password: 114514
postgres:
  dsn: postgres://u0yo8pkcngraa2dd:gUwrsPq3Jww9VM3PrTp0@b1p59qbrhfnnninh2ucx-mysql.services.clever-cloud.com:3306/b1p59qbrhfnnninh2ucx