openapi: 3.0.0
info:
  title: User management, authentication and authorization API
  version: 1.0.0
paths:
  /user:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  required: true
                  type: string
                password:
                  required: true
                  type: string
                email:
                  required: false
                  type: string
                nickname:
                  required: false
                  type: string
      responses:
        '201':
          description: User created
        '400':
          description: Invalid input
    get:
      summary: Get user info, whether by username or id
      requestHeaders:
        Authorization:
          required: true
          description: Bearer JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                id:
                  type: integer
      responses:
        '200':
          description: The specified user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  msg:
                    type: string
                    summary: Always empty
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      password:
                        type: string
                        summary: Always empty
                      email:
                        type: string
                      nickname:
                        type: string
        '401':
          description: Unauthorized
        '404':
          description: User not found

